package ch.interlis.ili2c;

public class CompilerTest {
	
	private static final String TEST_OUT="test/data/compiler/";
	
	// This test checks the help text of the compiler (--quiet -h)
	
	//		INTERLIS Compiler, Version 2.5.0-20041202
	//		  Distributed by the Coordination of Geographic Information
	//		  and Geographic Information Systems Group (COSIG), CH-3084 Wabern
	//		  Developed by Adasys AG, CH-8006 Zurich
	//		  Maintained by Eisenhut Informatik AG, CH-3303 Jegenstorf
	//		  See http://www.interlis.ch for information about INTERLIS
	//		  Parts of this program have been generated by ANTLR; see http://www.antlr.org
	//		  This product includes software developed by the
	//		  Apache Software Foundation (http://www.apache.org/).
	//
	//		DESCRIPTION
	//		  Parses and compiles INTERLIS Version 2.2 data model definitions.
	//		  Other options include conversion from INTERLIS Version 1 and back
	//		  (option -o1) and generation of an XML-Schema, released 2001 (option -oXSD).
	//
	//		USAGE
	//		  ili2c [Options] file1.ili -m meta1.xml file2.ili ...
	//
	//		OPTIONS
	//
	//		-o0                   Generate no output (default).
	//		-o1                   Generate INTERLIS-1 output.
	//		-o2                   Generate INTERLIS-2 output.
	//		-oXSD                 Generate an XML-Schema.
	//		-oFMT                 Generate an INTERLIS-1 Format.
	//		-oJAVA                Generate JAVA classes.
	//		-oIOM                 Generate Model as INTERLIS-Transfer (XTF).
	//		-c|--compare-with     Compare two or more model definitions.
	//		--check-metaobj       Check if referenced metaobjects exist.
	//		-boid Model.Basket=BOID  Define a mapping from a qualified basket
	//		                      name to a BOID of a metadata container.
	//		--with-predefined     Include the predefined MODEL INTERLIS in
	//		                      the output. Usually, this is omitted.
	//		--without-warnings    Report only errors, no warnings. Usually,
	//		                      warnings are generated as well.
	//		-h|--help             Display this help text.
	//		-u|--usage            Display short information about usage.
	//		-v|--version          Display the version of ili2c.
	//
	//		EXAMPLES
	//
	//		Check whether an INTERLIS definition in "file1.ili" is valid:
	//		    ili2c file1.ili
	//
	//		Check whether a definition distributed over several files is valid:
	//		    ili2c file1.ili file2.ili
	//
	//		Generate an INTERLIS-1 definition:
	//		    ili2c -o1 file1.ili file2.ili
	//
	//		Generate an INTERLIS-2 definition:
	//		    ili2c -o2 file1.ili file2.ili
	//
	//		Generate a definition of the predefined MODEL INTERLIS:
	//		    ili2c -o2 --with-predefined
	//
	//		Generate an XML-Schema:
	//		    ili2c -oXSD file1.ili file2.ili
	//
	//		Check whether two definitions are equivalent (e.g. de->fr):
	//		    ili2c de_1.ili de_2.ili -c fr_1.ili fr_2.ili
}